name: Publish OAS APIs
on:
  push:
    branches:
      - master
jobs:
  publish-oas-apis:
    uses: TykTechnologies/github-actions/.github/workflows/publish-oas-apis.yaml@publish-oas-apis 
    secrets:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      BASE_API_URL: ${{ secrets.BASE_API_URL }}
